apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: master
  name: master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: master
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: master
    spec:
      containers:
        - args:
            - /usr/spark/bin/spark-class
            - org.apache.spark.deploy.master.Master
            - -h
            - master
          env:
            - name: MASTER
              value: spark://master:7077
            - name: SPARK_CONF_DIR
              value: /conf
          image: deleteme
          name: master
          ports:
            - containerPort: 4040
            - containerPort: 6066
            - containerPort: 7077
            - containerPort: 8080
            - containerPort: 7001
            - containerPort: 7002
            - containerPort: 7003
            - containerPort: 7004
            - containerPort: 7005
            - containerPort: 7006
          resources: {}
          volumeMounts:
            - mountPath: /conf
              name: master-claim0
            - mountPath: /tmp/data
              name: master-claim1
      hostname: master
      restartPolicy: Always
      volumes:
        - name: master-claim0
          persistentVolumeClaim:
            claimName: master-claim0
        - name: master-claim1
          persistentVolumeClaim:
            claimName: master-claim1
status: {}
