apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: master
  name: master
spec:
  ports:
    - name: "4040"
      port: 4040
      targetPort: 4040
    - name: "6066"
      port: 6066
      targetPort: 6066
    - name: "7077"
      port: 7077
      targetPort: 7077
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "7001"
      port: 7001
      targetPort: 7001
    - name: "7002"
      port: 7002
      targetPort: 7002
    - name: "7003"
      port: 7003
      targetPort: 7003
    - name: "7004"
      port: 7004
      targetPort: 7004
    - name: "7005"
      port: 7005
      targetPort: 7005
    - name: "7006"
      port: 7006
      targetPort: 7006
    - name: 7077-tcp
      port: 7077
      targetPort: 7077
    - name: 6066-tcp
      port: 6066
      targetPort: 6066
  selector:
    io.kompose.service: master
status:
  loadBalancer: {}
