apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "7012"
      port: 7012
      targetPort: 7012
    - name: "7013"
      port: 7013
      targetPort: 7013
    - name: "7014"
      port: 7014
      targetPort: 7014
    - name: "7015"
      port: 7015
      targetPort: 7015
    - name: "7016"
      port: 7016
      targetPort: 7016
    - name: "8881"
      port: 8881
      targetPort: 8881
  selector:
    io.kompose.service: worker
status:
  loadBalancer: {}
